services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-mountain}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mountain-password}
      POSTGRES_DB: ${POSTGRES_DB:-mountain}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432

volumes:
  db:
